/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DeleteMapDraftArgs } from "./DeleteMapDraftArgs";
import { MapDraftFindManyArgs } from "./MapDraftFindManyArgs";
import { MapDraftFindUniqueArgs } from "./MapDraftFindUniqueArgs";
import { MapDraft } from "./MapDraft";
import { MapDraftService } from "../mapDraft.service";

@graphql.Resolver(() => MapDraft)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class MapDraftResolverBase {
  constructor(
    protected readonly service: MapDraftService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "MapDraft",
    action: "read",
    possession: "any",
  })
  async _mapDraftsMeta(
    @graphql.Args() args: MapDraftFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [MapDraft])
  @nestAccessControl.UseRoles({
    resource: "MapDraft",
    action: "read",
    possession: "any",
  })
  async mapDrafts(
    @graphql.Args() args: MapDraftFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<MapDraft[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "MapDraft",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => MapDraft, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "MapDraft",
    action: "read",
    possession: "own",
  })
  async mapDraft(
    @graphql.Args() args: MapDraftFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<MapDraft | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "MapDraft",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => MapDraft)
  @nestAccessControl.UseRoles({
    resource: "MapDraft",
    action: "delete",
    possession: "any",
  })
  async deleteMapDraft(
    @graphql.Args() args: DeleteMapDraftArgs
  ): Promise<MapDraft | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
