/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateStreamerArgs } from "./CreateStreamerArgs";
import { UpdateStreamerArgs } from "./UpdateStreamerArgs";
import { DeleteStreamerArgs } from "./DeleteStreamerArgs";
import { StreamerFindManyArgs } from "./StreamerFindManyArgs";
import { StreamerFindUniqueArgs } from "./StreamerFindUniqueArgs";
import { Streamer } from "./Streamer";
import { Tournament } from "../../tournament/base/Tournament";
import { StreamerService } from "../streamer.service";

@graphql.Resolver(() => Streamer)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class StreamerResolverBase {
  constructor(
    protected readonly service: StreamerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Streamer",
    action: "read",
    possession: "any",
  })
  async _streamersMeta(
    @graphql.Args() args: StreamerFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Streamer])
  @nestAccessControl.UseRoles({
    resource: "Streamer",
    action: "read",
    possession: "any",
  })
  async streamers(
    @graphql.Args() args: StreamerFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Streamer[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Streamer",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Streamer, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Streamer",
    action: "read",
    possession: "own",
  })
  async streamer(
    @graphql.Args() args: StreamerFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Streamer | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Streamer",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Streamer)
  @nestAccessControl.UseRoles({
    resource: "Streamer",
    action: "create",
    possession: "any",
  })
  async createStreamer(
    @graphql.Args() args: CreateStreamerArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Streamer> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Streamer",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Streamer"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        tournament: args.data.tournament
          ? {
              connect: args.data.tournament,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Streamer)
  @nestAccessControl.UseRoles({
    resource: "Streamer",
    action: "update",
    possession: "any",
  })
  async updateStreamer(
    @graphql.Args() args: UpdateStreamerArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Streamer | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Streamer",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Streamer"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          tournament: args.data.tournament
            ? {
                connect: args.data.tournament,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Streamer)
  @nestAccessControl.UseRoles({
    resource: "Streamer",
    action: "delete",
    possession: "any",
  })
  async deleteStreamer(
    @graphql.Args() args: DeleteStreamerArgs
  ): Promise<Streamer | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Tournament, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Streamer",
    action: "read",
    possession: "any",
  })
  async tournament(
    @graphql.Parent() parent: Streamer,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Tournament | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Tournament",
    });
    const result = await this.service.getTournament(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
