/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import {
  Prisma,
  Tournament,
  Asset,
  Map,
  Session,
  Streamer,
  Team,
} from "@prisma/client";

export class TournamentServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.TournamentFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.TournamentFindManyArgs>
  ): Promise<number> {
    return this.prisma.tournament.count(args);
  }

  async findMany<T extends Prisma.TournamentFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.TournamentFindManyArgs>
  ): Promise<Tournament[]> {
    return this.prisma.tournament.findMany(args);
  }
  async findOne<T extends Prisma.TournamentFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.TournamentFindUniqueArgs>
  ): Promise<Tournament | null> {
    return this.prisma.tournament.findUnique(args);
  }
  async create<T extends Prisma.TournamentCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.TournamentCreateArgs>
  ): Promise<Tournament> {
    return this.prisma.tournament.create<T>(args);
  }
  async update<T extends Prisma.TournamentUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.TournamentUpdateArgs>
  ): Promise<Tournament> {
    return this.prisma.tournament.update<T>(args);
  }
  async delete<T extends Prisma.TournamentDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.TournamentDeleteArgs>
  ): Promise<Tournament> {
    return this.prisma.tournament.delete(args);
  }

  async findAssets(
    parentId: string,
    args: Prisma.AssetFindManyArgs
  ): Promise<Asset[]> {
    return this.prisma.tournament
      .findUnique({
        where: { id: parentId },
      })
      .assets(args);
  }

  async findMaps(
    parentId: string,
    args: Prisma.MapFindManyArgs
  ): Promise<Map[]> {
    return this.prisma.tournament
      .findUnique({
        where: { id: parentId },
      })
      .maps(args);
  }

  async findSessions(
    parentId: string,
    args: Prisma.SessionFindManyArgs
  ): Promise<Session[]> {
    return this.prisma.tournament
      .findUnique({
        where: { id: parentId },
      })
      .sessions(args);
  }

  async findStreamers(
    parentId: string,
    args: Prisma.StreamerFindManyArgs
  ): Promise<Streamer[]> {
    return this.prisma.tournament
      .findUnique({
        where: { id: parentId },
      })
      .streamers(args);
  }

  async findTeams(
    parentId: string,
    args: Prisma.TeamFindManyArgs
  ): Promise<Team[]> {
    return this.prisma.tournament
      .findUnique({
        where: { id: parentId },
      })
      .teams(args);
  }
}
