/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateMapArgs } from "./CreateMapArgs";
import { UpdateMapArgs } from "./UpdateMapArgs";
import { DeleteMapArgs } from "./DeleteMapArgs";
import { MapFindManyArgs } from "./MapFindManyArgs";
import { MapFindUniqueArgs } from "./MapFindUniqueArgs";
import { Map } from "./Map";
import { TournamentFindManyArgs } from "../../tournament/base/TournamentFindManyArgs";
import { Tournament } from "../../tournament/base/Tournament";
import { MapService } from "../map.service";

@graphql.Resolver(() => Map)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class MapResolverBase {
  constructor(
    protected readonly service: MapService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Map",
    action: "read",
    possession: "any",
  })
  async _mapsMeta(
    @graphql.Args() args: MapFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Map])
  @nestAccessControl.UseRoles({
    resource: "Map",
    action: "read",
    possession: "any",
  })
  async maps(
    @graphql.Args() args: MapFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Map[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Map",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Map, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Map",
    action: "read",
    possession: "own",
  })
  async map(
    @graphql.Args() args: MapFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Map | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Map",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Map)
  @nestAccessControl.UseRoles({
    resource: "Map",
    action: "create",
    possession: "any",
  })
  async createMap(
    @graphql.Args() args: CreateMapArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Map> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Map",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Map"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Map)
  @nestAccessControl.UseRoles({
    resource: "Map",
    action: "update",
    possession: "any",
  })
  async updateMap(
    @graphql.Args() args: UpdateMapArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Map | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Map",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Map"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Map)
  @nestAccessControl.UseRoles({
    resource: "Map",
    action: "delete",
    possession: "any",
  })
  async deleteMap(@graphql.Args() args: DeleteMapArgs): Promise<Map | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Tournament])
  @nestAccessControl.UseRoles({
    resource: "Map",
    action: "read",
    possession: "any",
  })
  async tournament(
    @graphql.Parent() parent: Map,
    @graphql.Args() args: TournamentFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Tournament[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Tournament",
    });
    const results = await this.service.findTournament(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }
}
