/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { PlayerListRelationFilter } from "../../player/base/PlayerListRelationFilter";
import { TournamentListRelationFilter } from "../../tournament/base/TournamentListRelationFilter";
@InputType()
class TeamWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  logo?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  name?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => PlayerListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PlayerListRelationFilter)
  @IsOptional()
  @Field(() => PlayerListRelationFilter, {
    nullable: true,
  })
  players?: PlayerListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => TournamentListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TournamentListRelationFilter)
  @IsOptional()
  @Field(() => TournamentListRelationFilter, {
    nullable: true,
  })
  tournament?: TournamentListRelationFilter;
}
export { TeamWhereInput };
