/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DeleteMapDraftStatusArgs } from "./DeleteMapDraftStatusArgs";
import { MapDraftStatusFindManyArgs } from "./MapDraftStatusFindManyArgs";
import { MapDraftStatusFindUniqueArgs } from "./MapDraftStatusFindUniqueArgs";
import { MapDraftStatus } from "./MapDraftStatus";
import { MapDraftStatusService } from "../mapDraftStatus.service";

@graphql.Resolver(() => MapDraftStatus)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class MapDraftStatusResolverBase {
  constructor(
    protected readonly service: MapDraftStatusService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "MapDraftStatus",
    action: "read",
    possession: "any",
  })
  async _mapDraftStatusesMeta(
    @graphql.Args() args: MapDraftStatusFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [MapDraftStatus])
  @nestAccessControl.UseRoles({
    resource: "MapDraftStatus",
    action: "read",
    possession: "any",
  })
  async mapDraftStatuses(
    @graphql.Args() args: MapDraftStatusFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<MapDraftStatus[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "MapDraftStatus",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => MapDraftStatus, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "MapDraftStatus",
    action: "read",
    possession: "own",
  })
  async mapDraftStatus(
    @graphql.Args() args: MapDraftStatusFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<MapDraftStatus | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "MapDraftStatus",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => MapDraftStatus)
  @nestAccessControl.UseRoles({
    resource: "MapDraftStatus",
    action: "delete",
    possession: "any",
  })
  async deleteMapDraftStatus(
    @graphql.Args() args: DeleteMapDraftStatusArgs
  ): Promise<MapDraftStatus | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
